### ISSUE TITLE
Error on set_composer_variables.sh

### ISSUE THREAD

**Issue by msserpa** [GoogleCloudPlatform/ci-cd-for-data-processing-workflow#11]
I get the following error when executing set_composer_variables script on composer 1.17.2 airflow 2.12:

> ERROR: (gcloud.composer.environments.run) argument SUBCOMMAND: Must be specified.                                                                 
Usage: gcloud composer environments run (ENVIRONMENT : --location=LOCATION) SUBCOMMAND [SUBCOMMAND_NESTED] [optional flags] [-- CMD_ARGS ...]
  optional flags may be  --help | --location                                                                                                      

I fixed it by remove the extra '--' as follows:

`-  --location "${COMPOSER_REGION}" variables -- --set "${i}" "${variables[$i]}"`
`+  --location "${COMPOSER_REGION}" variables -- set "${i}" "${variables[$i]}"`

**Comment by kingman** [comment]
Fix in [PR](https://github.com/GoogleCloudPlatform/ci-cd-for-data-processing-workflow/pull/13)
