### ISSUE TITLE
Error on build_deploy_test.yaml

### ISSUE THREAD

**Issue by msserpa** [GoogleCloudPlatform/ci-cd-for-data-processing-workflow#12]
I get the following error on the build using composer 1.17.2 airflow 2.12:

> airflow variables command error: argument COMMAND: invalid choice: 'dataflow_jar_file_test' (choose from 'delete', 'export', 'get', 'import', 'list', 'set'), see help above.
command terminated with exit code 2
usage: airflow variables [-h] COMMAND ...
> ERROR: (gcloud.composer.environments.run) kubectl returned non-zero status code.

The solution was the same as #11 ,

`-  args: ['composer', 'environments', 'run', '${_COMPOSER_ENV_NAME}', '--location', '${_COMPOSER_REGION}','variables', '-', '--set', 'dataflow_jar_file_test', 'dataflow_deployment_$BUILD_ID.jar']`

`+  args: ['composer', 'environments', 'run', '${_COMPOSER_ENV_NAME}', '--location', '${_COMPOSER_REGION}','variables','--', 'set', 'dataflow_jar_file_test', 'dataflow_deployment_$BUILD_ID.jar']`

**Comment by kingman** [comment]
fixed in [PR](https://github.com/GoogleCloudPlatform/ci-cd-for-data-processing-workflow/pull/13)
